### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by mintar** [rock-core/base-doc#48]
The website has not been regenerated for at least a year or so. For example, bffdb33f has still not arrived on the [website](http://rock-robotics.org/stable/documentation/packages/outside_of_rock.html). I noticed because I was about to fix the same thing again.

**Comment by maltewi** [comment]
I wanted re-raise this issue. Website generation still seems to be down.

@planthaber, @doudou, @2maz : Does someone of you know what need to be done to get it running again?

**Comment by planthaber** [comment]
https://github.com/rock-core/base-admin_scripts/pull/2 has to be finished, I currently do not have time to care about the script.

On long term it would be nice to separate doc generation and Website content updates in a way that the content of base-doc is updated even if the doc genreration for all the packages fails

**Comment by maltewi** [comment]
Okay. Meanwhile, would it be possible to trigger the website generation manually. Commits come in slowly (every few months), so manually triggering would be feasible.

**Comment by planthaber** [comment]
"manual trigger" means executing the script mentioned.

**Comment by planthaber** [comment]
We just discussed to try to move the content from this repo to github pages, and only generate the package list and doxygen documentation "the old way".

The new page layout would include changing the "master/stable" documentation to be folder based. On each release the current "master" pages would be copied to a folder named by the release name and is not touched anymore, to preserve the documentation of that release in the state it was in at release time.

Any thoughts?

**Comment by doudou** [comment]
> We just discussed to try to move the content from this repo to github pages, and only generate the package list and doxygen documentation "the old way".

This sounds like the right approach. So some people are ready to convert this to jekyll ? This depends on webgen < 1.0 and will stop to be "generable" one way or the other.

My plan for the packages was to scrap the current system which is the real source of the problem, generate JSON files and have javascript generate the package browsing on the frontend.

**Comment by planthaber** [comment]
Did a update manually and wanted to do some documentation, the procedure is as follows:

Start a Ububntu 14.04 docker (ruby 1.8)

```
$> apt-get update
$> apt-get install git ruby-dev rubygems lftp

$> git config --global user.email "you@example.com"
$> git config --global user.name "Your Name"

$> git clone https://github.com/rock-core/base-doc.git
$> gem install cmdparse -v 2.0.6 --no-rdoc --no-ri
$> gem install kramdown -v 1.4.0 --no-rdoc --no-ri
$> gem install webgen -v 0.5.17 --no-rdoc --no-ri

$> cd base-doc

$> webgen

$> cd out
$> lfpt 
:~>open -u $UPLOAD_USER,$UPLOAD_PASSWD $FTP_URL
:~>mirror -v -R --only-newer --parallel=8 --delete --use-cache --exclude status/ ./ www/

```

**Comment by planthaber** [comment]
As this is docker approach works, I am wondering if we could stay on this webgen version and use a docker-based CI to push the static page to github.io.

**Comment by doudou** [comment]
It seems that the update broke access to https://www.rock-robotics.org/autoproj_bootstrap

**Comment by planthaber** [comment]
True, just fixed it.

The .htaccess file is not part of this template, when doing the update, i did a completely fresh upload.
I reinstalled the .htascess file from the backup.

We also lost master and stable versions of the website, but i guess this is ok for now, right?

**Comment by doudou** [comment]
> i guess this is ok for now, right?

Totally

**Comment by planthaber** [comment]
Hi,

@2maz, @kirishanthchethurajah: FYI

Kirishanth migrated the current website from webgen to jekyll, to be able to use github.io for the rock homepage:

Please check it here:
https://kirishanthchethurajah.github.io/

"browse packages" is broken, but that needs external tooling anyway, so not curetnly an issue.
Should we remove it?

If there is no issue, i'd propose moving the repo to rock-core and let the rock-robotics.org point to the github.io page.

But first need to fix redirects (e.g. https://www.rock-robotics.org/autoproj_bootstrap) in the .io page: Github has this enabled: https://github.com/jekyll/jekyll-redirect-from

**Comment by planthaber** [comment]
Any comments?

**Comment by 2maz** [comment]
IMO you can already move it to rock-core and then fix the redirection issue.

**Comment by doudou** [comment]
> Should we remove it?

I would say "yes"

**Comment by 2maz** [comment]
I migrated now the old base-doc webgen based content to jekyll and included some additional fixes.
Please @doudou @planthaber check if you spot remaining issues.
https://rock-core.github.io/documentation/index.html

**Comment by planthaber** [comment]
We could replace/remove the browse packages section.

Also the Core/Build system/Autoproj and autobuild API lkinks are broken.

**Comment by planthaber** [comment]
The Community Links is broken and we should decide it we should remove the "news", which were last updated 2015.

**Comment by 2maz** [comment]
> 
> 
> We could replace/remove the browse packages section.

Ack

> 
> Also the Core/Build system/Autoproj and autobuild API lkinks are broken.

Sure about that - these links are already fixed? Please ensure you did not accidentally jump to rock-robotics.org but stayed on https://rock-core.github.io/documentation/autoproj/index.html

**Comment by planthaber** [comment]
community now works, but new is a 404 now

**Comment by 2maz** [comment]
new is fixed now

**Comment by 2maz** [comment]
I activated a redirect from rock-robotics.org

**Comment by 2maz** [comment]
DNS Records have been updated so that rock-robotics.org is now pointing to the github.io page.
From my perspective the migration is completed and I will therefore close this issue. 

For issues with the updated website please use: https://github.com/rock-core/rock-core.github.io/issues or directly create a merge request https://github.com/rock-core/rock-core.github.io/pulls
